### ISSUE TITLE
@ as title crashes code

### ISSUE THREAD

**Issue by SzoDavid** [SzoDavid/MakeAStory#7]
When using the `/create` command if the title is '@', the bot will crash.

```
DiscordAPIError[50035]: Invalid Form Body
name[BASE_TYPE_REQUIRED]: This field is required
    at SequentialHandler.runRequest (/home/pi/dcbots/MakeAStory/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/pi/dcbots/MakeAStory/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/pi/dcbots/MakeAStory/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async ThreadManager.create (/home/pi/dcbots/MakeAStory/node_modules/discord.js/src/managers/ThreadManager.js:125:18)
    at async Object.execute (/home/pi/dcbots/MakeAStory/commands/create.js:29:18) {
  rawError: {
    code: 50035,
    errors: { name: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1011784521290616943/threads',
  requestBody: {
    files: undefined,
    json: {
      name: '@',
      auto_archive_duration: undefined,
      type: 11,
      invitable: undefined,
      rate_limit_per_user: undefined
    }
  }
}
```

**Comment by kovagoadi** [comment]
#8 
This should fix it.
